services:
  backend:
    image: ghcr.io/christianrazul/kkb-app-backend:${IMAGE_TAG:-latest}
    pull_policy: always

  web:
    image: ghcr.io/christianrazul/kkb-app-web:${IMAGE_TAG:-latest}
    pull_policy: always
